name: Upload to APT Repo
description: Upload multiple .deb packages to the specified APT repository.
inputs:
  repo-token:
    description: "GitHub token to access the apt-repo repository"
    required: true
  codename:
    description: "Codename of the repository (e.g., bookworm, trixie-testing)"
    required: true
  package-paths:
    description: "Paths to the .deb packages to upload, separated by commas"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install -y reprepro gnupg git

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ameridroid/apt-repo
        path: /repo

    - name: Import GPG key
      shell: bash
      env:
        GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_KEY" | gpg --import
        gpg --list-keys

    - name: Upload packages to APT repository
      shell: bash
      run: |
        cd /repo
        IFS=',' read -r -a packages <<< "${{ inputs.package-paths }}"
        for package in "${packages[@]}"; do
          reprepro -b /repo --ignore=wrongdistribution includedeb "${{ inputs.codename }}" "$package"
        done

    - name: Push updated repository to main branch
      shell: bash
      run: |
        cd /repo
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Update APT repository for ${{ inputs.codename }}"
        git push origin main
